apiVersion: v1
kind: PersistentVolume
metadata:
  name: dir-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/admin/study/coursework/kubernetes/data/